job_finder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jobs.urls')),
]

jobs/urls.py
from django.urls import path

from .views import HomePageView, SearchResultsView

urlpatterns = [
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('', HomePageView.as_view(), name='index'),
]

jobs/models.py
from django.db import models

class Job(models.Model):
    url = models.CharField(max_length=250, unique=True)
    title = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    description = models.TextField()
    posted_date = models.DateField()
    company_name = models.CharField(max_length=250)
    job_board_site = models.CharField(max_length=250)

    class Meta:
        # table name
        db_table = 'job'

class JobPostBanList(models.Model):
    url = models.CharField(max_length=250, unique=True)

class CompanyBanList(models.Model):
    company_name = models.CharField(max_length=250, unique=True)

jobs/forms.py
from django import forms

class RawQueryForm(forms.Form):
    raw_query = forms.CharField(label='raw query', max_length=256)

jobs/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect

from .models import Job, CompanyBanList, JobPostBanList

import re

class HomePageView(TemplateView):
    template_name = 'index.html'

class SearchResultsView(ListView):
    model = Job
    template_name = 'search_results.html'
    
    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        '''
        Runs raw query and returns result
        '''
        raw_query: str = self.request.GET.get('raw_query')
        return Job.objects.raw(raw_query)

    def post(self, request):
        '''
        Handles buttons in search result page
        '''
        if 'ban_company' in request.POST:
            banned_company_name = request.POST.get('company_name')
            CompanyBanList.objects.get_or_create(company_name=banned_company_name)
            Job.objects.filter(company_name=banned_company_name).delete()
            # return redirect('/search/?raw_query=' + request.GET.get('raw_query'))
        elif 'delete_job_post' in request.POST:
            delete_url = request.POST.get('url')
            Job.objects.filter(url=delete_url).delete()
        elif 'ban_job_post' in request.POST:
            ban_url = request.POST.get('url')
            JobPostBanList.objects.get_or_create(url=ban_url)
            Job.objects.filter(url=ban_url).delete()
        response = HttpResponse()
        return response

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Job Dashboard</title>

        <!-- Load CSS -->
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    </head>
    <body style="background-color:lightblue;">
        <!-- Heading -->
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Job Dashboard</a>
        </nav>
        <br>

        <!-- Query Form -->
        <div class="form_wrapper">
            <form action="{% url 'search_results' %}" method="GET">
                <div class="form-group row form_row">
                    <p>Insert a SQL statement to query in <b>Job</b> table</p>
                    <textarea id="raw_query" rows="5" cols="200" name="raw_query">SELECT * FROM Job LIMIT 1;</textarea>
                </div>
                <div class="form-group row form_row">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
        
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

templates/search_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <title>Job Dashboard</title>

        <!-- Load CSS -->
        <link rel="stylesheet" href="{% static 'css/search_results.css' %}">
    </head>
    <body style="background-color:lightblue;">
        <!-- Heading -->
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="/">Job Dashboard</a>
        </nav>

        <!-- Query Results -->
        <div class="result_wrapper">
            <p>Found {{ job_list|length }} job(s)</p>
            <br/>
            <table class="table-bordered">
                {% for job in job_list %}
                <tbody>
                    <tr>
                        <!-- Buttons Column -->
                        <td class="btn_td">
                            <div class="btn_div">
                                <!-- Ban Company -->
                                <form method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="company_name" value="{{ job.company_name }}">
                                    <button type="submit" class="btn btn-danger" name="ban_company">Ban Company</button>
                                </form>
                                <form method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="url" value="{{ job.url }}">
                                    <button type="submit" class="btn btn-danger" name="delete_job_post">Delete Job Post</button>
                                </form>
                                <form method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="url" value="{{ job.url }}">
                                    <button type="submit" class="btn btn-danger" name="ban_job_post">Ban Job Post</button>
                                </form>
                                
                            </div>
                        </td>
                        <!-- Job Post Column -->
                        <td class="job_td">
                            <div class="job_div">
                                <a href="{{ job.url }}"><h2>{{ job.title }} | {{ job.location }} | {{ job.company_name }}</h2></a>
                                <h5>{{ job.job_board_site }} | {{ job.posted_date }}</h5>
                                <hr/>
                                <p>{{ job.description }}</p>
                            </div>
                        </td>
                    </tr>
                </tbody>
                {% endfor %}
            </table>
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>
<!-- https://stackoverflow.com/questions/11336548/django-taking-values-from-post-request
https://docs.djangoproject.com/en/dev/ref/request-response/#httprequest-objects -->